# Zabbix Config for Remote Update Script for Debian Systems v3 - by databloat
# https://github.com/databloat/zabbix-debian-updates
#
# Collector unprivileged as JSON
UserParameter=debian.update.status,/etc/zabbix/scripts/zbx_remote_update.sh check

AllowKey=system.run[sudo /etc/zabbix/scripts/zbx_remote_update.sh apply]
